### ISSUE TITLE
Logo div obscures clickable area on links

### ISSUE THREAD

**Issue by kethinov** [MayOneUS/mayday-2.0-frontend#12]
`<div class="container">` covers the clickable links making it so only part of the text is clickable.

![screen shot 2015-02-25 at 12 13 51 pm](https://cloud.githubusercontent.com/assets/419567/6375913/5dc5750e-bce8-11e4-8ddd-6e46e56decf4.png)

**Comment by Rio517** [comment]
Ah.  I noticed, but I hadn't investigated further - thinks for doing so.  I'm passing on to @jparker165 as we have a asana task that references this.

**Comment by Rio517** [comment]
Resolved with c8181710cb4a173d31181b91504c94b10d3a0e53

**Comment by benjamindsinger** [comment]
You can ignore this comment, I'm just testing a github workaround to quickly add images. ![m](https://cloud.githubusercontent.com/assets/13975934/11127097/07dfbc54-8938-11e5-8f9d-130749fb8b5e.png)
