### ISSUE TITLE
jekyll-assets required?

### ISSUE THREAD

**Issue by matt2000** [MayOneUS/mayday-2.0-frontend#179]
It seems like the jekyll-assets plugin is required, but not mentioned in the README. I tried `gem install jekyll-assets` which let the build success, but left my pages with references to non-existent asset/[random-id].js files. Is a specific version of jekyll-assets required?

**Comment by Rio517** [comment]
I should have added a recent change to the readme.  You  will need to run
`bundle install` first, assuming you have bundler installed.  `gem insall
bundler`

**Comment by matt2000** [comment]
OK, that installed a bunch of gems of different versions, so it seems to be on the right path, but I'm now getting from `jekyll build`:

```
WARN: Unresolved specs during Gem::Specification.reset:
      celluloid (~> 0.16.0)
      ffi (>= 0.5.0)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
```

Even though it included those 2 packages at supported versions from the `bundle install`. What to do? I'm not familiar with the Ruby ecosystem, so I might be missing something "obvious" to a trained rubyist.

**Comment by Rio517** [comment]
Try to delete the Gemfile.lock, run bundle install and see if that helps.
Sorry not in front of a computer to see what is up.

-Mario

**Comment by matt2000** [comment]
No luck. I also tried restoring the Gemfile.lock from the repository & rerunning bundle install.

**Comment by Rio517** [comment]
Darn. Will have to look at it later.  Are you using Ruby 2.2.2?

-Marii

**Comment by matt2000** [comment]
No, 2.1.2p95. Should I update?

**Comment by Rio517** [comment]
If you can,  that might help.  Are you using rvm?

**Comment by Rio517** [comment]
Hum...  I tried, but couldn't reproduce this issue. 

```
rvm install 2.1.2 -l 95 #install ruby using rvm
gem install bundler #install bundler
bundle install #install gem dependecies
jekyll server #start jekyll server
```

Since you only got a warning, it should have still run the build process.  If you run server, is the server up and running at localhost:4000?

**Comment by Rio517** [comment]
Readme is updated to reflect the new start up process.

**Comment by Rio517** [comment]
How did it go, Matt?

**Comment by Rio517** [comment]
No luck?

**Comment by Rio517** [comment]
I'm assuming no more input is needed here, reopen if you need help.
