### ISSUE TITLE
Header render glitch in Firefox

### ISSUE THREAD

**Issue by kethinov** [MayOneUS/mayday-2.0-frontend#7]
Left: Chrome
Right: Firefox

Tested on OS X.

The curved header graphic is pixelated. @Rio517 can you look into this?

![screen shot 2015-02-21 at 6 13 05 pm](https://cloud.githubusercontent.com/assets/419567/6318527/16c69078-ba65-11e4-8a40-028dbc87d2b6.png)

**Comment by Rio517** [comment]
I believe this has been fixed.  Can you pull the latest and confirm?

**Comment by kethinov** [comment]
Looked fixed now.
